site_name: Drew C.
site_url: https://drewcam.github.io
site_author: Drew C.
site_description: A personal Docs and Blog site.

# Repository

repo_name: DrewCam/drewcam.github.io
repo_url: https://github.com/DrewCam/drewcam.github.io

#extra_css:
#  - stylesheets/extra.css
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: cyan

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  language: en

plugins:
  - blog
  - tags
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      enable_creation_date: true

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/DrewCam
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/drew-cam/
    - icon: simple/credly
      link: https://www.credly.com/users/drew-cameron

nav:
  - Home: index.md
  - Blog: blog/index.md
  - obsidian:
    - obsidian/index.md
    - task callouts: obsidian/task-callouts.md
  #  - About: about.md
