authors:
  drewcam:
    name: Drew C                                              # Author name
    description: Cyber Security Analyst                       # Author description
    avatar: https://avatars.githubusercontent.com/u/5970574   # Author avatar
    url: https://github.com/DrewCam                           # Author website URL