name: ci

on:
  push:
    branches:
      - master
      - main

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x' # You can specify a different Python version if necessary

      - name: Upgrade pip, setuptools, and wheel
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Dependencies
        run: |
          pip install mkdocs-material \
                      mkdocs-awesome-pages-plugin \
                      mkdocs-git-revision-date-localized-plugin
 
      - name: Build and Deploy
        run: mkdocs gh-deploy --force

      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
